# Generated by Django 4.2.9 on 2025-03-09 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxpayers', '0002_alter_payer_doctor_alter_payer_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpcExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxpayers.payer')),
            ],
        ),
        migrations.CreateModel(
            name='BpcAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocolo', models.CharField(max_length=50)),
                ('servico', models.CharField(max_length=200)),
                ('situacao', models.CharField(max_length=100)),
                ('data_abertura', models.DateTimeField()),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('unidade', models.CharField(max_length=200)),
                ('detalhes', models.JSONField(default=dict)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bpc.bpcexecution')),
            ],
        ),
    ]
