# Generated by Django 4.2.9 on 2025-03-10 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpcatendimento',
            options={'ordering': ['-data_solicitacao'], 'verbose_name': 'Atendimento BPC', 'verbose_name_plural': 'Atendimentos BPC'},
        ),
        migrations.RemoveField(
            model_name='bpcatendimento',
            name='data_abertura',
        ),
        migrations.RemoveField(
            model_name='bpcatendimento',
            name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='bpcatendimento',
            name='detalhes',
        ),
        migrations.RemoveField(
            model_name='bpcatendimento',
            name='unidade',
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='acompanha_processo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='anexos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='campos_adicionais',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='canal_requerente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='cpf_requerente',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='cpf_solicitante',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='data_protocolo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='data_solicitacao',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='nome_requerente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='solicitante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='unidade_protocolo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='unidade_responsavel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bpcatendimento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bpcatendimento',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bpcatendimento',
            name='servico',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bpcatendimento',
            name='situacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bpcexecution',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
