# Generated by Django 4.2.9 on 2025-03-22 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpc', '0002_alter_bpcatendimento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpcexecution',
            options={'ordering': ['-execution_date']},
        ),
    ]
