# Generated by Django 4.2.9 on 2024-01-28 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('payer_name', models.CharField(max_length=255)),
                ('partner', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('initial_requirement', models.CharField(max_length=4000)),
                ('inss_requirement', models.CharField(max_length=4000)),
                ('doctor', models.BooleanField()),
                ('social', models.BooleanField()),
                ('der', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
