# Generated by Django 4.2.9 on 2025-03-03 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('finished', models.BooleanField()),
                ('finished_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('passwd', models.CharField(blank=True, max_length=255)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('partner', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('initial_requirement', models.CharField(blank=True, max_length=4000)),
                ('inss_requirement', models.CharField(blank=True, max_length=4000)),
                ('doctor', models.BooleanField()),
                ('social', models.BooleanField()),
                ('daily_update', models.BooleanField(default=False)),
                ('der', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayerUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('situation', models.CharField(max_length=50)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxpayers.payer')),
            ],
            options={
                'verbose_name': 'Atualização do Contribuinte',
                'verbose_name_plural': 'Atualizações do Contribuinte',
                'db_table': 'payer_updates',
                'ordering': ['created_at'],
            },
        ),
    ]
