# Generated by Django 4.2.9 on 2025-03-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payer',
            name='social',
            field=models.BooleanField(default=False),
        ),
    ]
