# Generated by Django 4.2.9 on 2025-03-22 00:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateField(null=True)),
                ('execution_period', models.IntegerField(help_text='Tempo de execução automática (em minutos)')),
                ('autenticado', models.BooleanField(default=False, help_text='Define se o sistema está autenticado')),
                ('finished', models.BooleanField()),
                ('finished_at', models.DateField()),
            ],
        ),
    ]
